version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: pocketjob-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pocketjob
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pocketjob"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: